version: '3.8'

services:
  php:
    build:
      context: .
    container_name: php-container
    volumes:
      - .:/var/www/html
    ports:
      - "8083:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
